language: cpp

compiler:
  - gcc

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir Build
  - cd Build
  - mkdir Debug
  - cd Debug
  - cmake ../.. -DCMAKE_BUILD_TYPE=Debug
  - make
  - make test ARGS="-V"
  - cd ..
  - mkdir Release
  - cd Release
  - cmake ../.. -DCMAKE_BUILD_TYPE=Release
  - make
  - make test ARGS="-V"
