language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - PACKAGE_NAME=Linux_gcc7
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
        - PACKAGE_NAME=Linux_clang7
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
        - PACKAGE_NAME=Linux_clang8
    - os: osx
      osx_image: xcode10
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - PACKAGE_NAME=OSX_XCode10
    - os: osx
      osx_image: xcode11
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - PACKAGE_NAME=OSX_XCode11
    - os: osx
      osx_image: xcode12
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - PACKAGE_NAME=OSX_XCode12

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir Build
  - cd Build
  - mkdir Debug
  - cd Debug
  - cmake ../.. -DCMAKE_BUILD_TYPE=Debug
  - make
  - make test ARGS="-V"
  - make install
  - cd ..
  - cd ..
  - python CreatePackage.py Build/Debug/DevKit ${PACKAGE_NAME}_Debug
  - cd Build
  - mkdir Release
  - cd Release
  - cmake ../.. -DCMAKE_BUILD_TYPE=Release
  - make
  - make test ARGS="-V"
  - make install
  - cd ..
  - cd ..
  - python CreatePackage.py Build/Release/DevKit ${PACKAGE_NAME}_Release
  - cd Build
  - mkdir RelWithDebInfo
  - cd RelWithDebInfo
  - cmake ../.. -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - make
  - make test ARGS="-V"
  - make install
  - cd ..
  - cd ..
  - python CreatePackage.py Build/RelWithDebInfo/DevKit ${PACKAGE_NAME}_RelWithDebInfo

deploy:
  provider: releases
  api_key:
    secure: oN14X2NG9+1O6cVQ7m2pIUkMxJ4mbZC1oht03WtJPS4E03MfPH8wZYAw9vmkSL9H
  file_glob: true
  file: Build/Package/*
  skip_cleanup: true
  on:
    tags: true
