language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - PACKAGE_NAME=Linux_gcc7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - PACKAGE_NAME=Linux_gcc8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        - PACKAGE_NAME=Linux_gcc9
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
        - PACKAGE_NAME=Linux_clang7
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
        - PACKAGE_NAME=Linux_clang8
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
        - PACKAGE_NAME=Linux_clang9
    - os: osx
      osx_image: xcode10.3
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - PACKAGE_NAME=OSX_XCode10_3
    - os: osx
      osx_image: xcode11
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - PACKAGE_NAME=OSX_XCode11
    - os: osx
      osx_image: xcode11.6
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - PACKAGE_NAME=OSX_XCode11_6
    - os: osx
      osx_image: xcode12
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - PACKAGE_NAME=OSX_XCode12

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir Build
  - cd Build
  - mkdir Debug
  - cd Debug
  - cmake ../.. -DCMAKE_BUILD_TYPE=Debug
  - make
  - make test ARGS="-V"
  - make install
  - cd ..
  - cd ..
  - python CreatePackage.py Build/Debug/DevKit ${PACKAGE_NAME} Debug
  - cd Build
  - mkdir Release
  - cd Release
  - cmake ../.. -DCMAKE_BUILD_TYPE=Release
  - make
  - make test ARGS="-V"
  - make install
  - cd ..
  - cd ..
  - python CreatePackage.py Build/Release/DevKit ${PACKAGE_NAME} Release
  - cd Build
  - mkdir RelWithDebInfo
  - cd RelWithDebInfo
  - cmake ../.. -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - make
  - make test ARGS="-V"
  - make install
  - cd ..
  - cd ..
  - python CreatePackage.py Build/RelWithDebInfo/DevKit ${PACKAGE_NAME} RelWithDebInfo
