language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-7
          packages:
            - clang-7
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
    - os: osx
      osx_image: xcode10
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: osx
      osx_image: xcode11
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir Build
  - cd Build
  - mkdir Debug
  - cd Debug
  - cmake ../.. -DCMAKE_BUILD_TYPE=Debug
  - make
  - make test ARGS="-V"
  - cd ..
  - mkdir Release
  - cd Release
  - cmake ../.. -DCMAKE_BUILD_TYPE=Release
  - make
  - make test ARGS="-V"
  - mkdir RelWithDebInfo
  - cd RelWithDebInfo
  - cmake ../.. -DCMAKE_BUILD_TYPE=RelWithDebInfo
  - make
  - make test ARGS="-V"
