dist: trusty
language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

script:
  - mkdir Build
  - cd Build
  - mkdir Debug
  - cd Debug
  - cmake ../.. -DCMAKE_BUILD_TYPE=Debug
  - make
  - make test
  - cd ..
  - cd Release
  - cmake ../.. -DCMAKE_BUILD_TYPE=Release
  - make
  - make test
