version: "{build}"

clone_folder: c:\projects\VisualScriptEngine

image:
  - Visual Studio 2017

cache:
  - C:\Dependencies -> appveyor.yml

configuration:
  - Debug
  - Release

platform:
  - x64

before_build:
  - python installdepswin.py C:\Dependencies msbuild
  - set WXWIDGETS_DIR=C:\Dependencies\wxWidgets-3.1.2
  - mkdir Build
  - cd Build
  - cmake -G "Visual Studio 15 2017 Win64" ..

build:
  project: c:\projects\VisualScriptEngine\Build\VisualScriptEngine.sln
  verbosity: minimal

test_script:
  - ctest --verbose --build-config %configuration%
