version: "{build}"

clone_folder: c:\projects\VisualScriptEngine

image:
  - Visual Studio 2017

configuration:
  - Debug
  - Release

platform:
  - x64

before_build:
  - mkdir Build
  - cd Build
  - cmake -G "Visual Studio 15 2017 Win64" ..

build:
  project: %APPVEYOR_BUILD_FOLDER%\Build\VisualScriptEngine.sln
  verbosity: minimal

test_script:
  - %APPVEYOR_BUILD_FOLDER%\Build\%CONFIGURATION%\NodeEngineTest.exe
