version: "{build}"

clone_folder: c:\projects\VisualScriptEngine

image:
  - Visual Studio 2017

configuration:
  - Debug
  - Release

platform:
  - x64

before_build:
  - set DEPENDENCIES_FOLDER=C:\Dependencies\
  - python installdepswin.py %DEPENDENCIES_FOLDER% msbuild
  - mkdir Build
  - cd Build
  - cmake -G "Visual Studio 15 2017 Win64" ..

build:
  project: c:\projects\VisualScriptEngine\Build\VisualScriptEngine.sln
  verbosity: minimal

test_script:
  - ctest --verbose --build-config %configuration%
