version: "{build}"

clone_folder: c:\projects\VisualScriptEngine

image:
  - Visual Studio 2017
  - Visual Studio 2019

configuration:
  - Debug
  - Release
  - RelWithDebInfo

platform:
  - x64

init:
- set cMakeParams=
- if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( set cMakeParams=-G "Visual Studio 15 2017 Win64" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2019" ( set cMakeParams=-G "Visual Studio 16 2019" -A "x64")

before_build:
  - mkdir Build
  - cd Build
  - cmake %cMakeParams% ..
  - cd ..

build:
  project: c:\projects\VisualScriptEngine\Build\VisualScriptEngine.sln
  verbosity: minimal

after_build:
  - set vsVersion=
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( set vsVersion=2017 )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2019" ( set vsVersion=2019 )
  - python CreateDevKit.py "MSBuild" %configuration%
  - python CreatePackage.py VS%vsVersion%_%configuration%

test_script:
  - cd Build
  - ctest --verbose --build-config %configuration%
  - cd ..

artifacts:
  - path: Build\Package\*

deploy:
  description: 'Release Description'
  provider: GitHub
  auth_token:
    secure: oN14X2NG9+1O6cVQ7m2pIUkMxJ4mbZC1oht03WtJPS4E03MfPH8wZYAw9vmkSL9H
  draft: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
