version: "{build}"

clone_folder: c:\projects\VisualScriptEngine

image:
  - Visual Studio 2017

cache:
  - C:\Dependencies\wxWidgets-3.1.2\include -> appveyor.yml
  - C:\Dependencies\wxWidgets-3.1.2\lib\vc_x64_lib -> appveyor.yml

configuration:
  - Debug
  - Release

platform:
  - x64

before_build:
  - set WXWIDGETS_DIR=C:\Dependencies\wxWidgets-3.1.2
  - python installdepswin.py C:\Dependencies msbuild %configuration%
  - mkdir Build
  - cd Build
  - cmake -G "Visual Studio 15 2017 Win64" ..

build:
  project: c:\projects\VisualScriptEngine\Build\VisualScriptEngine.sln
  verbosity: minimal

test_script:
  - ctest --verbose --build-config %configuration%
